# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 882484b359aa7056fb18f20f8dadf1562e1fffedd29d15b1d66de922e40c0785487054f68b7cede01c79223dc5339ff7cc5cb9abf3d20611cd97d557a009776d

test:
  secret_key_base: 3480b3c45fad6e0aa05df86ee87142369e666b512f012788d578d6819198050a044fed5d035a3fd972ebd970fcc065c9ed3c0b3f0ba0f31cd588303d0ba31837

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
